config/routes.rb
Rails.application.routes.draw do
  resources :authors

  resources :editorials

  resources :books

  get 'home/index'
  root to: 'home#index'

  devise_for :users
  
  

end

app/models/author.rb
# == Schema Information
#
# Table name: Authors
#
#  id               :integer          not null, primary key
#  name            :string(255)      not null




class Author < ActiveRecord::Base
	has_many :book

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id               :integer          not null, primary key
#  title            :string(255)      not null
#  author           :string(255)      not null
#  editorial        :string(255)      not null
#  original_title   :string(255)
#  translation      :string(255)
#  edition          :integer
#  edition_date     :date
#  edition_place    :string(255)
#  publication_year :integer
#  isbn             :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Book < ActiveRecord::Base
  belongs_to:editorial
  belongs_to:author 
  has_attached_file :cover, :styles => { :medium => "200x200>", :thumb => "64x64>" }, :default_url => "missing.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
  validates :title, :author, :editorial, :presence => true
  validates :edition, :publication_year, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true

	def self.search(search)
		if search
		  joins(:author).joins(:editorial).where('title LIKE ? OR edition LIKE ? OR authors.name LIKE ? OR editorials.name LIKE ?',"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
		  
		else
		  where(nil)
		end
	end
  
end

app/models/editorial.rb
# == Schema Information
#
# Table name: Editorials
#
#  id               :integer          not null, primary key
#  name            :string(255)      not null


class Editorial < ActiveRecord::Base
	has_many :book
	accepts_nested_attributes_for :book, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  email              :string(255)      default(""), not null
#  encrypted_password :string(255)      default(""), not null
#  sign_in_count      :integer          default(0), not null
#  current_sign_in_at :datetime
#  last_sign_in_at    :datetime
#  current_sign_in_ip :string(255)
#  last_sign_in_ip    :string(255)
#  failed_attempts    :integer          default(0), not null
#  locked_at          :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :lockable, :trackable, :timeoutable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  respond_to :html
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
    respond_with(@authors)
  end

  def show
    respond_with(@author)
  end

  def new
    @author = Author.new
    respond_with(@author)
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    @author.save
    respond_with(@author)
  end

  def update
    @author.update(author_params)
    respond_with(@author)
  end

  def destroy
    @author.destroy
    respond_with(@author)
  end

  private
    def set_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :html
  require 'will_paginate/array' 
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction 

  def index

    @books = Book.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new

    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
 
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  def sort_direction  
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"  
  end
  def sort_column  
    Book.column_names.include?(params[:sort]) ? params[:sort] : "title"  
  end 

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:cover,:title, :author, :editorial, :original_title, :translation, :edition, :edition_date, :edition_place, :publication_year, :isbn,:editorial_id,:author_id)
    end
end

app/controllers/editorials_controller.rb
class EditorialsController < ApplicationController
  respond_to :html
  before_action :set_editorial, only: [:show, :edit, :update, :destroy]

  def index
    @editorials = Editorial.all
    respond_with(@editorials)
  end

  def show
    respond_with(@editorial)
  end

  def new
    @editorial = Editorial.new
    respond_with(@editorial)
  end

  def edit
  end

  def create
    @editorial = Editorial.new(editorial_params)
    @editorial.save
    respond_with(@editorial)
  end

  def update
    @editorial.update(editorial_params)
    respond_with(@editorial)
  end

  def destroy
    @editorial.destroy
    respond_with(@editorial)
  end

  private
    def set_editorial
      @editorial = Editorial.find(params[:id])
    end

    def editorial_params
      params.require(:editorial).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.nil?
      redirect_to new_user_session_path
    else
      redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end  

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for @book, :html=> {multipart: true} do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cover %><br>
    <%= f.file_field :cover , class:"form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.collection_select :author_id, Author.all, :id, :name,{},{class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :editorial %><br>
 <%= f.collection_select :editorial_id, Editorial.all, :id, :name,{},{class: "form-control"} %>


   

  </div>
  <div class="form-group">
    <%= f.label :original_title %><br>
    <%= f.text_field :original_title  , class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :translation %><br>
    <%= f.text_field :translation , class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :edition %><br>
    <%= f.number_field :edition , class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :edition_date %><br>
    <div class="form-inline">
    <%= f.date_select :edition_date , {:order => [:day, :month, :year], :start_year => 1910, :end_year => 2020}, {:class => 'form-control'}  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :edition_place %><br>
    <%= f.text_field :edition_place , class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :publication_year %><br>
    <%= f.number_field :publication_year ,  {:class => "form-control"} %>

  </div>
  <div class="form-group">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn  , class:"form-control"%>
  </div>
  <div class="actions">
    <%= f.submit nil , class:"btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @book , :class => 'btn btn-default'%> 
<%= link_to 'Back', books_path , :class => 'btn btn-default'%>

app/views/books/index.html.erb
<% content_for :title, "Lista de libros" %>
<div id="books_index">
  <h1><%= yield :title %></h1>

  <% if @books.blank? %>
    <div class="alert alert-warning">No hay libros que mostrar</div>
  <% else %>
    <%= form_tag books_path, :method => 'get' do %>  
  <p>  
    <div class="form-inline">
    <%= text_field_tag :search, params[:search],:class => "form-control",:placeholder=>"Ingrese un termino..." %>  
    <%= submit_tag "Buscar", :title => nil, :class=>"btn btn-primary" %> 
    </div> 
  </p>  
<% end %>  
    <div class="responsive-fake-table expansible-fake-table">
      <header class="row">
 
        <div class="col col-xs-5 col-sm-4 col-md-3"><%=
            sortable "title", t('activerecord.attributes.book.title')
        %></div>
        <div class="col col-xs-5 col-sm-3 col-md-3"><%= sortable "author" ,t('activerecord.attributes.book.author')%></div>
        <div class="col hidden-xs col-sm-4 col-md-3"><%= sortable "editorial" ,t('activerecord.attributes.book.editorial')%></div>
        <div class="col hidden-xs hidden-sm col-md-2"><%= sortable "edition" ,t('activerecord.attributes.book.edition')%></div>
        <div class="col col-xs-2 col-sm-1 col-md-1"><span class="hidden-sm hidden-xs">Opciones</span>&nbsp;</div>
      </header>
      <% @books.each do |book|%>
        <section class="row">

          <div class="col col-xs-5 col-sm-4 col-md-3 toggle"><%=book.title %></div>
          <div class="col col-xs-5 col-sm-3 col-md-3 toggle"><%=book.author.name%></div>
          <div class="col hidden-xs col-sm-4 col-md-3 toggle"><%=book.editorial.name%></div>
          <div class="col hidden-xs hidden-sm col-md-2 toggle"><%=book.edition%></div>
          <div class="col col-xs-2 col-sm-1 col-md-1">
            <%= link_to content_tag('i','', class: 'fa fa-eye'), book, class: 'tooltipable', title: 'Ver' %>
            <%= link_to content_tag('i','', class: 'fa fa-pencil-square-o'), edit_book_path(book), class: 'tooltipable', title: 'Editar' %>
            <%= link_to content_tag('i','', class: 'fa fa-times'), book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tooltipable', title: 'Eliminar' %>
        
          </div>
          <div class="col col-xs-12 panel-collapse collapse">
            <dl class="dl-horizontal">
               

              <dt class="visible-xs"><%=t('activerecord.attributes.book.editorial') %></dt>
              <dd class="visible-xs"><%=book.editorial || '-' %></dd>
              

              <dt ><%=t('activerecord.attributes.book.cover') %></dt>
              <dd><%=image_tag book.cover.url('thumb'), class: 'img-thumbnail' %></dd>

              <dt><%=t('activerecord.attributes.book.original_title') %></dt>
              <dd><%=book.original_title || '-' %></dd>
              
              <dt class="visible-xs visible-sm"><%=t('activerecord.attributes.book.edition') %></dt>
              <dd class="visible-xs visible-sm"><%=book.edition || '-' %></dd>
              
              <dt><%=t('activerecord.attributes.book.edition_date') %></dt>
              <dd><%=book.edition_date.present? ? l(book.edition_date) : '-' %></dd>
              
              <dt><%=t('activerecord.attributes.book.publication_year') %></dt>
              <dd><%=book.publication_year || '-' %></dd>
              
              <dt></dt>
              <dd>
              </dd>
            </dl>
            <%= link_to 'Ver más', book, class: 'btn btn-default btn-xs more-book-btn' %>                
          </div>
        </section>
      <% end %>
    </div>

  <% end %>
 <div class="row">
  <div class="text-center">
     <%= will_paginate @books, previous_label: "<", next_label: ">", renderer: BootstrapPagination::Rails %>
  </div>
 </div>
  
  <%= link_to 'Agregar libro', new_book_path, class: 'btn btn-primary' %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<% content_for :title, "Ver libro: #{@book.title}" %>
<div id="books_show">
  <h1><%= yield :title %></h1>
  <div class="col-md-8">
  <dl class="dl-horizontal">
    <dt><%=t('activerecord.attributes.book.title') %></dt>
    <dd><%=@book.title || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.author') %></dt>
    <dd><%=@book.author.name || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.editorial') %></dt>
    <dd><%=@book.editorial.name || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.original_title') %></dt>
    <dd><%=@book.original_title || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.translation') %></dt>
    <dd><%=@book.translation || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.edition') %></dt>
    <dd><%=@book.edition || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.edition_date') %></dt>
    <dd><%=if @book.edition_date.present? then l(@book.edition_date) else '-' end %></dd>
    <dt><%=t('activerecord.attributes.book.edition_place') %></dt>
    <dd><%=@book.edition_place || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.publication_year') %></dt>
    <dd><%=@book.publication_year || '-' %></dd>
    <dt><%=t('activerecord.attributes.book.isbn') %></dt>
    <dd><%=@book.isbn || '-' %></dd>
  </dl>
  </div>
  <div class="col-md-4">
    <%=image_tag @book.cover.url('medium'), class: 'img-thumbnail'  %>
  </div>

  <div class="row">
    <div class="col-sm-offset-1 col-sm-11">      
      <%= link_to 'Editar', edit_book_path(@book), class: 'btn btn-primary' %>
      <%= link_to 'Volver', books_path, class: 'btn btn-default' %>
    </div>
  </div>

app/views/editorials/_form.html.erb
<%= form_for(@editorial) do |f| %>
  <% if @editorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editorial.errors.count, "error") %> prohibited this editorial from being saved:</h2>

      <ul>
      <% @editorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editorials/edit.html.erb
<h1>Editing editorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @editorial %> |
<%= link_to 'Back', editorials_path %>

app/views/editorials/index.html.erb
<h1>Listing editorials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editorials.each do |editorial| %>
      <tr>
        <td><%= editorial.name %></td>
        <td><%= link_to 'Show', editorial %></td>
        <td><%= link_to 'Edit', edit_editorial_path(editorial) %></td>
        <td><%= link_to 'Destroy', editorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Editorial', new_editorial_path %>

app/views/editorials/new.html.erb
<h1>New editorial</h1>

<%= render 'form' %>

<%= link_to 'Back', editorials_path %>

app/views/editorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @editorial.name %>
</p>

<%= link_to 'Edit', edit_editorial_path(@editorial) %> |
<%= link_to 'Back', editorials_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<p><%if user_signed_in? %>
  Hola <%= current_user.as_json.inspect %> - <%=link_to 'salir', destroy_user_session_path, :method => :delete  %> 
  <% else %>
  <%= link_to 'ingresar', new_user_session_path %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>La biblio<%= (" :: " + yield(:title)) if content_for?(:title)  %></title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user.present? %>
    <header>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapsible-at-xs">
              <span class="sr-only">Abre / cierra la navegación</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'La biblio', root_path, class: 'navbar-brand'%>
          </div>
          
          <div class="collapse navbar-collapse" id="main-navbar-collapsible-at-xs">
            
            
            
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%=link_to destroy_user_session_path, :method => :delete do %>
                  salir <i class="fa fa-sign-out"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <% end %>
  
  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>